In [1]:
import numpy as np
from numpy.matlib import repmat

In [2]:
def scheduler1():
    B1 = np.array([0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0])
    B2 = np.array([0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])
    
    B = [B1, B2]
    
    return 42, B

In [3]:
def scheduler2():
    B1 = np.array([0, 1, 0, 0, 0, 0]) 
    B2 = np.array([0, 1, 0, 0, 0, 0, 0, 0])
    
    B = [B1, B2]
    
    return 32, B

In [4]:
def scheduler3():
    B1 = np.array([0, 1, 0, 0, 0, 0])   
    B2 = np.array([0, 1, 0, 0, 0, 0, 0, 0])
    B3 = np.array([0, 0, 0, 0, 0, 1, 0, 0, 0, 0])
    
    B = [B1, B2, B3]
    
    return 32, B

In [5]:
def scheduler4():
    B1 = np.array([0, 0, 0, 1, 0, 1, 0])
    B2 = np.array([0, 1, 0, 1, 0, 0, 0, 0, 0])
    
    B = [B1, B2]
    
    return 28, B

In [6]:
def scheduler5():
    B1 = np.array([0, 0, 0, 1, 0, 1, 0])
    B2 = np.array([0, 1, 0, 1, 0, 0, 0, 0, 0])
    B3 = np.array([0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1])
    
    B = [B1, B2, B3]
    
    return 33, B

In [7]:
def scheduler6():
    B0 = np.array([0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1])
    B1 = np.array([0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0])
    B2 = np.array([0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0])
    
    B = [B0, B1, B2]
    
    return 150, B

In [8]:
def scheduler7():
    B0 = np.array([0, 0, 0, 0, 0])
    B1 = np.array([0, 0, 0, 0, 0, 1, 0])
    B2 = np.array([0, 0, 1, 0, 0, 0, 0, 0, 0])
    
    B = [B0, B1, B2]
    
    return 150, B

In [9]:
def scheduler8():
    B0 = np.array([0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0])
    B1 = np.array([0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0])
    B2 = np.array([0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0])
    
    B = [B0, B1, B2]
    
    return 150, B

In [10]:
def scheduler9():
    B0 = np.array([0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0])
    B1 = np.array([0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0])
    B2 = np.array([0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0])
    B3 = np.array([0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0])
    
    B = [B0, B1, B2, B3]
    
    return 150, B

In [11]:
def scheduler10():
    B0 = np.array([0, 1, 1, 0, 1, 0])
    B1 = np.array([0, 0, 0, 0, 1, 1, 1, 0])
    B2 = np.array([0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0])
    
    return 50, [B0, B1, B2]
    

In [12]:
def scheduler11():
    B0 = np.array([0, 1, 1, 0, 1, 0])
    B1 = np.array([0, 0, 0, 0, 1, 1, 1, 0])
    B2 = np.array([0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0])
    B3 = np.array([0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0])
    
    return 50, [B0, B1, B2, B3]

In [13]:
def lcm(array):
    return np.lcm.reduce(array)

In [26]:
def coincidence(bins, n_max):
    flags = np.zeros(4)
    n_PRF = len(bins)
    L = [row.shape[0] for row in bins]
    Lu_max = lcm(L)
    print(L, Lu_max)
    n_det = [np.count_nonzero(row) for row in bins]
    # Target missed
    flags[0] = not(all(n_det))

    for i in range(n_PRF):
        # Repeat array
        n_rep = int(np.floor(n_max/L[i])) + 1
        bins[i] = np.tile(bins[i], (1, n_rep))
        
    big = max([row.shape[1] for row in bins])
    for i in range(n_PRF):
        # match array length to concatenate
        e = big-bins[i].shape[1]
        bins[i] = np.pad(bins[i], [(0,0), (0,e)], mode='constant')
        
    match = np.concatenate(bins)
    index = np.where(match.sum(axis=0) == n_PRF)[0]
    
    # Long range ambiguity
    flags[1] = np.logical_and(Lu_max < index, index < n_max).any()
    # Too many targets
    flags[2] = len(index) > max(n_det)
    
    
    return index, flags
    

In [30]:
a, b = scheduler1()
c = coincidence(b, a)
c
b[0].shape

[12, 14] 84


(1, 56)

In [31]:
a, b = scheduler2()
c = coincidence(b, a)
c
b[0].shape

[6, 8] 24


(1, 40)

In [29]:
a, b = scheduler3()
c = coincidence(b, a)
c

[6, 8, 10] 120


(array([25], dtype=int64), array([0., 0., 0., 0.]))

In [18]:
a, b = scheduler4()
c = coincidence(b, a)
c

(array([ 3, 10, 12, 19], dtype=int64), array([0., 0., 1., 0.]))

In [19]:
a, b = scheduler5()
c = coincidence(b, a)
c

(array([10, 12], dtype=int64), array([0., 0., 0., 0.]))

In [20]:
a, b = scheduler6()
c = coincidence(b, a)
c

(array([79, 87], dtype=int64), array([0., 0., 0., 0.]))

In [21]:
a, b = scheduler7()
c = coincidence(b, a)
c

(array([], dtype=int64), array([1., 0., 0., 0.]))

In [22]:
a, b = scheduler8()
c = coincidence(b, a)
c

(array([ 27,  57,  60, 108, 112], dtype=int64), array([0., 0., 1., 0.]))

In [23]:
a, b = scheduler9()
c = coincidence(b, a)
c

(array([ 27,  60, 108, 112], dtype=int64), array([0., 0., 0., 0.]))

In [24]:
a, b = scheduler10()
c = coincidence(b, a)
c

(array([13, 20, 22, 37, 44, 46], dtype=int64), array([0., 1., 1., 0.]))

In [25]:
a, b = scheduler11()
c = coincidence(b, a)
c

(array([13, 20, 46], dtype=int64), array([0., 0., 0., 0.]))